config/routes.rb
PersonalSite::Application.routes.draw do

 	resources :blogs
  devise_for :users

 	root :to => 'pages#home'

 	match '/about', to: 'pages#about'
 	match '/blog', to: 'pages#blog'
 	match '/contact', to: 'pages#contact'
 	match '/feedback', to: 'pages#feedback'
 	match '/portfolio', to: 'pages#portfolio'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def blog
    @blog = Blog.all
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= provide(:title, 'Blogs') %>

<%= render 'layouts/header' %>
<div class="blog_container">
  <div class="blog_table"><br />
  <% @blogs.each do |blog| %><br />
      <strong><%= blog.title %></strong><br /><br />
      <div class="blog_body"><%= blog.body %></div><br /><br />
      <div class="date_time">Posted <%= time_ago_in_words(blog.created_at) %> ago</div>
      <div class="blog_border"></div>
  <% end %>
  </div>
</div>
  <br />
<%= render 'layouts/footer' %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Body:</b>
  <%= @blog.body %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.keithasazawa.com"> Keith Asazawa</a>
  </small>
  <nav>
    <ul>
    	<li><%= link_to "Blog", blogs_path %></li>
      <li><%= link_to "Feedback", feedback_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <div class="container">
      <div class="blue"></div>
			<div class="left_nav">
        <li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Portfolio", portfolio_path %></li>
  		</div>
      <div class="right_nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>          
      </div>
      <div class="center">
      	<%= link_to "Keith Asazawa", root_path, id: "logo" %>
    	</div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Exo:100' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Over+the+Rainbow' rel='stylesheet' type='text/css'>
  <title>Keith Asazawa | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<%= provide(:title, 'About') %>
<%= render 'layouts/header' %>
<div class="body">
	<!-- <h1>All About Me!</h1> -->
	<div class="picture">
	</div>
	<div class="about_me">
		<div class="about_title">
			<h4>About Me</h4>
			<div class="top_border"></div>
		</div>
		<div class="about_info">
			<p>WHO // KEITH ASAZAWA</p>
			<p>WHAT // FRONT AND BACK END WEB DEVELOPER</p>
			<p>WHERE // BAY AREA, CA</p>
			<p>WHEN // 2012 - PRESENT</p>
			<p>WHY // I LOVE {CODE}</p>
		</div>
		<div class="bottom_border"></div>
		<div class="skills">
			<h6>Skills</h6>
			<p>HTML, CSS, Javascript, PHP, Ruby on Rails</p>
		</div>
	</div>
</div>
<%= render 'layouts/footer' %>

app/views/pages/blog.html.erb
<%= provide(:title, 'Blog') %>
<%= render 'layouts/header' %>
<div class="body">
	
</div>
<%= render 'layouts/footer' %>

app/views/pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<%= render 'layouts/header' %>
<div class="body">
	<h2 id="contact_me">Contact me, I'd love to hear from you.</h2>
	<div class="contact_info">	
		<form>
			<div>
				<label class="form-name">Your name</label>
				<input id="name" type="text" name="name" placeholder=" Name"/>		
				<label class="form-name">Email Address</label>
				<input id="email" type="text" name="email" placeholder=" Email address"/>
				<label class="form-name">Message</label>
				<textarea id="feedback" name="feedback" placeholder=" Message"></textarea>
				<input type="button" value="Submit" id="button" />
			</div>
		</form>
	</div>
</div>
<%= render 'layouts/footer' %>

app/views/pages/home.html.erb
<%= provide(:title, 'Home') %>

<%= render 'layouts/header' %>

<div class="body">
	<div class="body_heading">
		<h1>HELLO.</h1>
	</div>
	<div class="body_image">
	</div>
	<div class="body_info">
		<h5>I'm a web developer</h5>
		<h3>born and raised in</h3>
		<h2>Oakland, California</h2>
	</div>
</div>

<%= render 'layouts/footer' %>

app/views/pages/portfolio.html.erb
<%= provide(:title, 'Portfolio') %>
<%= render 'layouts/header' %>
<div class="body">

</div>
<%= render 'layouts/footer' %>